---
# Retrieve token from master host

- name: "Register token stdout"
  shell: "kubeadm token create --print-join-command"
  become: yes
  register: join_command_raw

- name: "Register token fact"
  set_fact:
    join_command: "{{ join_command_raw.stdout_lines[0] }}"
